name: Build, Test and Check

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - '.gitignore'
      - '.mergify.yml'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  dispatcher:
    runs-on: ubuntu-22.04
    if: >- # Prevents running the workflow twice on PR made by a branch of the same repository
      github.event_name != 'pull_request'
      || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - run: 'true'

  build:
    needs:
      - dispatcher
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        jvm-version: [ 11, 17, 21 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up JDK ${{ matrix.jvm-version }}
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm-version }}
      - name: Assemble main and test classes
        run: ./gradlew classes testClasses
      - name: Test
        run: ./gradlew test
      - name: Check
        run: ./gradlew check

  success:
    needs:
      - build
    if: >- # run if at least one needed job has failed or all needed jobs have not been cancelled or skipped
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || (
          !contains(join(needs.*.result, ','), 'cancelled') 
          && !contains(join(needs.*.result, ','), 'skipped')
        )
      )
    runs-on: ubuntu-22.04
    steps:
      - name: Verify no failures occurred in needed jobs
        # if there are failures, false is executed and the job fails.
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}

  deploy:
    needs:
      - success
    uses: ./.github/workflows/publish.yml
    if: github.ref_name == 'master' || github.ref_name == 'main'
    secrets: inherit

  publish-api-doc:
    needs:
      - success
    uses: ./.github/workflows/dokka-gh-pages.yml
    if: github.ref_name == 'master' || github.ref_name == 'main'
    secrets: inherit
